name: Deploy AngularJS App to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  docker-build-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/g0e1b2e8

      - name: Build and Push Docker Image
        env:
          ECR_REPOSITORY: assignment1-angularjscicd2
        run: |
          docker build -t $ECR_REPOSITORY .
          docker tag $ECR_REPOSITORY:latest public.ecr.aws/g0e1b2e8/$ECR_REPOSITORY:latest
          docker push public.ecr.aws/g0e1b2e8/$ECR_REPOSITORY:latest

  deploy-to-ec2:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and Deploy Application
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            docker pull public.ecr.aws/g0e1b2e8/assignment1-angularjscicd2:latest
            docker stop angular-app || true
            docker rm angular-app || true
            docker run -d -p 80:80 --name angular-app public.ecr.aws/g0e1b2e8/assignment1-angularjscicd2:latest
