name: CI/CD Pipeline for AngularJS App

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  docker-build-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      #- name: Login to Amazon ECR
        #id: login-ecr
        #uses: aws-actions/amazon-ecr-login@v2
       # with:
          #registry-type: public
         # aws-region: us-east-1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URL }}

      - name: Build, Tag & Push Docker Image
        run: |
          docker build -t angular-app .
          docker tag angular-app:latest ${{ secrets.AWS_ECR_URL }}/angular-app:latest
          docker push ${{ secrets.AWS_ECR_URL }}/angular-app:latest

      
     

  deploy-to-ec2:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and Deploy Application
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            docker pull ${{ steps.login-ecr.outputs.registry }}/angular-app:latest
            docker stop angular-app || true
            docker rm angular-app || true
            docker run -d -p 80:80 --name angular-app ${{ steps.login-ecr.outputs.registry }}/angular-app:latest

